server:
  port: 8084
spring:
  application:
    name: menu-service
  datasource:
    url: jdbc:mysql://localhost:3306/menu_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
