server:
  port: 8085
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:configserver:http://localhost:8888/rabbitmq.yml
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
